
export default new Map([
["src/content/artikel/belajar-dari-alam-untuk-menjadi-tidak-sempurna.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fartikel%2Fbelajar-dari-alam-untuk-menjadi-tidak-sempurna.mdx&astroContentModuleFlag=true")],
["src/content/artikel/book-1-chapter-3-sabrina-si-penangkap-emosi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fartikel%2Fbook-1-chapter-3-sabrina-si-penangkap-emosi.mdx&astroContentModuleFlag=true")],
["src/content/artikel/book-1-chapter-4-kesurupan.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fartikel%2Fbook-1-chapter-4-kesurupan.mdx&astroContentModuleFlag=true")],
["src/content/artikel/ajakan-untuk-berpikir-sederhana-memahami-filosofi-awal-memulai-perjalanan-spiritual.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fartikel%2Fajakan-untuk-berpikir-sederhana-memahami-filosofi-awal-memulai-perjalanan-spiritual.mdx&astroContentModuleFlag=true")],
["src/content/artikel/book-1-chapter-6-teman-baru-teman-dari-kecil.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fartikel%2Fbook-1-chapter-6-teman-baru-teman-dari-kecil.mdx&astroContentModuleFlag=true")],
["src/content/artikel/book-1-chapter-7-5-gadis-misterius-dan-aromanya.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fartikel%2Fbook-1-chapter-7-5-gadis-misterius-dan-aromanya.mdx&astroContentModuleFlag=true")],
["src/content/artikel/book-1-chapter-7-dimensi-transisi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fartikel%2Fbook-1-chapter-7-dimensi-transisi.mdx&astroContentModuleFlag=true")],
["src/content/artikel/cita-cita.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fartikel%2Fcita-cita.mdx&astroContentModuleFlag=true")],
["src/content/artikel/mari-kita-bicara-tentang-kematian.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fartikel%2Fmari-kita-bicara-tentang-kematian.mdx&astroContentModuleFlag=true")],
["src/content/artikel/book-1-chapter-8-akhir-sesuatu-adalah-awal-yang-baru.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fartikel%2Fbook-1-chapter-8-akhir-sesuatu-adalah-awal-yang-baru.mdx&astroContentModuleFlag=true")]]);
		