name: Sync Fork to Main Repo

on:
  push:
    branches:
      - main

jobs:
  sync-back:
    # Hanya berjalan jika dijalankan di repositori fork milik akun kedua
    if: github.repository == 'Irham-ridwan/web-snu'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Main Repo
        run: |
          git push https://x-access-token:${{ secrets.MAIN_REPO_SYNC_TOKEN }}@github.com/PaKu211/web-snu.git main:main
